export const ACTION_TYPE = {
	GET_VIDEOS: "GET_VIDEOS",
	ADD_TO_LIKE: "ADD_TO_LIKE",
	REMOVE_FROM_LIKE: "REMOVE_FROM_LIKE",
	GET_LIKED_VIDEOS: "GET_LIKED_VIDEOS",
	GET_PLAYLIST: "GET_PLAYLIST",
	CREATE_PLAYLIST: "CREATE_PLAYLIST",
	DELETE_PLAYLIST: "DELETE_PLAYLIST",
	SHOW_MODAL: "SHOW_MODAL",
	HIDE_MODAL: "HIDE_MODAL",
	GET_PLAYLIST_VIDEOS: "GET_PLAYLIST_VIDEOS",
	ADD_TO_PLAYLIST: "ADD_TO_PLAYLIST",
	REMOVE_FROM_PLAYLIST: "REMOVE_FROM_PLAYLIST",
};
